{% set version = "0.0.4" %}

package:
  name: roundrobin
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/r/roundrobin/roundrobin-{{ version }}.tar.gz
    sha256: 7e9d19a5bd6123d99993fb935fa86d25c88bb2096e493885f61737ed0f5e9abd
  # TODO: remove after https://github.com/linnik/roundrobin/pull/2
  - url: https://raw.githubusercontent.com/linnik/roundrobin/master/LICENSE
    sha256: cadda19b588293f4fe19c2386eb476bc8387eb3d03ff5c9f22b08848328ff5fd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - roundrobin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/linnik/roundrobin
  summary: Collection of roundrobin utilities
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
